import { StoreTemplateDTO, StoreTheme, StoreSection } from "@/types/store-builder";

export const STARTER_TEMPLATES: StoreTemplateDTO[] = [
  // 1. Nova Fashion
  {
    id: "tpl-nova-fashion",
    templateId: "tpl-nova-fashion",
    name: "Nova Fashion",
    slug: "nova-fashion",
    category: "Fashion & Apparel",
    description: "Trendsetting fashion storefront featuring bold editorial imagery, interactive category tiles, and high-impact conversion blocks.",
    tags: ["fashion", "clothing", "streetwear", "apparel", "trendy"],
    style: "modern",
    thumbnail: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80",
    previewImage: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200&auto=format&fit=crop&q=80",
    isFeatured: true,
    viewsCount: 1420,
    usageCount: 88,
    version: 1,
    status: "PUBLISHED",
    supportedFeatures: ["whatsapp_checkout", "responsive_catalog", "size_guide", "quick_view"],
    productLayout: {
      columnsDesktop: 4,
      columnsMobile: 2,
      cardStyle: "modern",
      showQuickBuy: true,
      showWishlist: true,
      showRating: true,
      badgePosition: "top-left",
    },
    mobileSettings: {
      stickyBottomNav: true,
      compactHeader: true,
      gridColumns: 2,
    },
    themeConfig: {
      style: "fashion",
      colors: {
        primary: "#E11D48",
        secondary: "#BE123C",
        accent: "#F43F5E",
        background: "#FFFFFF",
        surface: "#FFF1F2",
        text: "#0F172A",
        mutedText: "#64748B",
        headerBg: "#FFFFFF",
        footerBg: "#0F172A",
        footerText: "#F8FAFC",
      },
      fonts: {
        heading: "Playfair Display",
        body: "Inter",
      },
      borderRadius: "lg",
      headerLayout: "standard",
      showAnnouncementBar: true,
      announcementText: "✨ NEW SEASON SALE: Get free express delivery on orders over Le 300!",
      announcementBg: "#E11D48",
      announcementTextColor: "#FFFFFF",
    },
    navigation: {
      header: [
        { id: "n-1", label: "Home", url: "/", isExternal: false },
        { id: "n-2", label: "New Arrivals", url: "#products", isExternal: false },
        { id: "n-3", label: "Women", url: "#categories", isExternal: false },
        { id: "n-4", label: "Men", url: "#categories", isExternal: false },
        { id: "n-5", label: "Contact", url: "#contact", isExternal: false },
      ],
      footer: [
        { id: "f-1", label: "Shop All", url: "#products", isExternal: false },
        { id: "f-2", label: "Size Guide", url: "#about", isExternal: false },
        { id: "f-3", label: "Delivery Policy", url: "#about", isExternal: false },
        { id: "f-4", label: "WhatsApp Support", url: "#contact", isExternal: false },
      ],
    },
    sections: [
      {
        id: "sec-hero",
        type: "hero",
        order: 1,
        visible: true,
        settings: { alignment: "left", overlay: true },
        content: {
          badge: "SUMMER COLLECTION 2026",
          headline: "Redefine Your Everyday Aesthetic",
          subheadline: "Explore bespoke silhouettes, vibrant contemporary streetwear, and handcrafted premium essentials designed to turn heads.",
          primaryCtaText: "Explore Collection",
          primaryCtaLink: "#products",
          secondaryCtaText: "Browse Lookbook",
          secondaryCtaLink: "#categories",
          imageUrl: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1200&auto=format&fit=crop&q=80",
          stats: [
            { label: "Curated Styles", value: "250+" },
            { label: "Happy Shoppers", value: "4.8k" },
            { label: "Customer Rating", value: "4.9/5" },
          ],
        },
      },
      {
        id: "sec-categories",
        type: "categories",
        order: 2,
        visible: true,
        settings: {},
        content: {
          title: "Curated Collections",
          subtitle: "Explore high-fashion apparel grouped for your unique lifestyle",
          categories: [
            { name: "Urban Streetwear", count: "48 items", image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&auto=format&fit=crop&q=80" },
            { name: "Evening & Gala", count: "32 items", image: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600&auto=format&fit=crop&q=80" },
            { name: "Accessories & Bags", count: "64 items", image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop&q=80" },
            { name: "Footwear Line", count: "29 items", image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop&q=80" },
          ],
        },
      },
      {
        id: "sec-products",
        type: "product-grid",
        order: 3,
        visible: true,
        settings: { limit: 8, columns: 4 },
        content: {
          title: "Trending Drops",
          subtitle: "Handpicked weekly bestsellers loved by our fashion community",
        },
      },
      {
        id: "sec-promo",
        type: "promotional-offer",
        order: 4,
        visible: true,
        settings: {},
        content: {
          badge: "EXCLUSIVE DROP",
          title: "Get 20% Off Your First Outfit",
          description: "Sign up or order via WhatsApp right now to claim your first-order welcome discount. Limited quantities available.",
          ctaText: "Claim Discount via WhatsApp",
          ctaLink: "#contact",
          endDate: "2026-12-31",
        },
      },
      {
        id: "sec-testimonials",
        type: "testimonials",
        order: 5,
        visible: true,
        settings: {},
        content: {
          title: "Loved by Fashion Enthusiasts",
          subtitle: "Real stories from verified trendsetters who shop with us",
          testimonials: [
            { name: "Fatmata K.", role: "Stylist & Model", comment: "The fabric quality and stitching exceeded all expectations. Fast delivery directly to Aberdeen!", rating: 5 },
            { name: "Mohamed B.", role: "Creative Director", comment: "Finally an online store with modern aesthetics and instant WhatsApp confirmation. 10/10 service.", rating: 5 },
          ],
        },
      },
      {
        id: "sec-contact",
        type: "contact",
        order: 6,
        visible: true,
        settings: {},
        content: {
          title: "Visit Our Showroom or Chat",
          subtitle: "Our fashion consultants are online 24/7 to assist with sizing and tailored recommendations.",
        },
      },
      {
        id: "sec-footer",
        type: "footer",
        order: 7,
        visible: true,
        settings: {},
        content: {
          aboutText: "Nova Fashion brings world-class apparel, modern footwear, and bespoke looks straight to your doorstep.",
          copyright: "© 2026 Nova Fashion. Powered by ProTech Assist Enterprise OS.",
        },
      },
    ],
  },

  // 2. Luxe Boutique
  {
    id: "tpl-luxe-boutique",
    templateId: "tpl-luxe-boutique",
    name: "Luxe Boutique",
    slug: "luxe-boutique",
    category: "Fashion & Apparel",
    description: "Ultra-premium, high-fashion layout with black-and-gold accents, serif typography, and bespoke editorial curation.",
    tags: ["luxury", "boutique", "couture", "designer", "gold"],
    style: "luxury",
    thumbnail: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&auto=format&fit=crop&q=80",
    previewImage: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=1200&auto=format&fit=crop&q=80",
    isFeatured: true,
    viewsCount: 1180,
    usageCount: 64,
    version: 1,
    status: "PUBLISHED",
    supportedFeatures: ["whatsapp_checkout", "responsive_catalog", "luxury_packaging", "vip_consultation"],
    productLayout: {
      columnsDesktop: 3,
      columnsMobile: 1,
      cardStyle: "elevated",
      showQuickBuy: true,
      showWishlist: true,
      showRating: false,
      badgePosition: "top-right",
    },
    mobileSettings: {
      stickyBottomNav: true,
      compactHeader: false,
      gridColumns: 1,
    },
    themeConfig: {
      style: "luxury",
      colors: {
        primary: "#D97706",
        secondary: "#B45309",
        accent: "#FBBF24",
        background: "#09090B",
        surface: "#18181B",
        text: "#FAFAFA",
        mutedText: "#A1A1AA",
        headerBg: "#09090B",
        footerBg: "#040405",
        footerText: "#D4D4D8",
      },
      fonts: {
        heading: "Playfair Display",
        body: "Cinzel",
      },
      borderRadius: "none",
      headerLayout: "centered",
      showAnnouncementBar: true,
      announcementText: "COMPLIMENTARY CONCIERGE PACKAGING & PRIVATE SHOWROOM APPOINTMENTS",
      announcementBg: "#D97706",
      announcementTextColor: "#09090B",
    },
    navigation: {
      header: [
        { id: "n-1", label: "The Atelier", url: "/", isExternal: false },
        { id: "n-2", label: "Haute Couture", url: "#products", isExternal: false },
        { id: "n-3", label: "Private Collection", url: "#featured", isExternal: false },
        { id: "n-4", label: "Concierge", url: "#contact", isExternal: false },
      ],
      footer: [
        { id: "f-1", label: "Private Client Services", url: "#contact", isExternal: false },
        { id: "f-2", label: "Authenticity Certificate", url: "#about", isExternal: false },
        { id: "f-3", label: "Bespoke Tailoring", url: "#contact", isExternal: false },
      ],
    },
    sections: [
      {
        id: "sec-hero",
        type: "hero",
        order: 1,
        visible: true,
        settings: { alignment: "center", overlay: true },
        content: {
          badge: "HAUTE HORLOGERIE & COUTURE",
          headline: "Elegance in Its Purest Form",
          subheadline: "Impeccable craftsmanship, rare fabrics, and bespoke tailoring designed for the discerning individual.",
          primaryCtaText: "Discover The Collection",
          primaryCtaLink: "#products",
          secondaryCtaText: "Book Concierge",
          secondaryCtaLink: "#contact",
          imageUrl: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=1200&auto=format&fit=crop&q=80",
        },
      },
      {
        id: "sec-products",
        type: "product-grid",
        order: 2,
        visible: true,
        settings: { limit: 6, columns: 3 },
        content: {
          title: "The Signature Gallery",
          subtitle: "Limited-edition masterpieces crafted with timeless elegance",
        },
      },
      {
        id: "sec-about",
        type: "about",
        order: 3,
        visible: true,
        settings: {},
        content: {
          title: "Artistry Without Compromise",
          description: "Every item in our atelier is meticulously inspected and authenticated. We uphold the finest standards of luxury retail.",
        },
      },
      {
        id: "sec-contact",
        type: "contact",
        order: 4,
        visible: true,
        settings: {},
        content: {
          title: "Private Client Advisory",
          subtitle: "Connect with your personal stylist for private consultations and custom orders.",
        },
      },
    ],
  },

  // 3. StreetWear Club
  {
    id: "tpl-streetwear",
    templateId: "tpl-streetwear",
    name: "StreetWear Club",
    slug: "streetwear-club",
    category: "Fashion & Apparel",
    description: "Bold, raw, and high-energy urban streetwear aesthetic with neon contrasts, oversized typography, and drop countdowns.",
    tags: ["streetwear", "urban", "skater", "hoodies", "sneakers", "bold"],
    style: "bold",
    thumbnail: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80",
    previewImage: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=1200&auto=format&fit=crop&q=80",
    isFeatured: false,
    viewsCount: 890,
    usageCount: 42,
    version: 1,
    status: "PUBLISHED",
    supportedFeatures: ["whatsapp_checkout", "responsive_catalog", "drop_countdown"],
    productLayout: {
      columnsDesktop: 4,
      columnsMobile: 2,
      cardStyle: "bordered",
      showQuickBuy: true,
      showWishlist: true,
      showRating: true,
      badgePosition: "top-left",
    },
    mobileSettings: {
      stickyBottomNav: true,
      compactHeader: true,
      gridColumns: 2,
    },
    themeConfig: {
      style: "bold",
      colors: {
        primary: "#F97316",
        secondary: "#EA580C",
        accent: "#FACC15",
        background: "#0A0A0C",
        surface: "#141419",
        text: "#FFFFFF",
        mutedText: "#9CA3AF",
        headerBg: "#0A0A0C",
        footerBg: "#000000",
        footerText: "#E5E7EB",
      },
      fonts: {
        heading: "Plus Jakarta Sans",
        body: "Inter",
      },
      borderRadius: "none",
      headerLayout: "standard",
      showAnnouncementBar: true,
      announcementText: "🔥 DROP 04 IS LIVE — LIMITED QUANTITIES PER PIECE",
      announcementBg: "#F97316",
      announcementTextColor: "#000000",
    },
    sections: [
      {
        id: "sec-hero",
        type: "hero",
        order: 1,
        visible: true,
        settings: { alignment: "left" },
        content: {
          badge: "NEW DROP 04",
          headline: "UNFILTERED URBAN STREET CULTURE",
          subheadline: "Heavyweight hoodies, graphic tees, cargos, and limited capsule pieces crafted for the streets.",
          primaryCtaText: "Cop The Drop",
          primaryCtaLink: "#products",
          imageUrl: "https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=1200&auto=format&fit=crop&q=80",
        },
      },
      {
        id: "sec-products",
        type: "product-grid",
        order: 2,
        visible: true,
        settings: { limit: 8, columns: 4 },
        content: {
          title: "Latest Drops",
          subtitle: "Grab yours before the capsule sells out forever",
        },
      },
      {
        id: "sec-promo",
        type: "promotional-offer",
        order: 3,
        visible: true,
        settings: {},
        content: {
          badge: "SNEAKERHEAD ALERT",
          title: "Buy 2 Tees, Get 1 Cap Free",
          description: "Automatic bundle applied on checkout. WhatsApp fast delivery available.",
          ctaText: "Order Via WhatsApp",
          ctaLink: "#contact",
        },
      },
    ],
  },

  // 4. TechHub Pro
  {
    id: "tpl-techhub",
    templateId: "tpl-techhub",
    name: "TechHub Pro",
    slug: "techhub-pro",
    category: "Electronics & Tech",
    description: "Modern high-tech gadget store with specs badges, warranty highlights, tech category pills, and device comparisons.",
    tags: ["tech", "electronics", "gadgets", "phones", "laptops", "apple"],
    style: "electronics",
    thumbnail: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&auto=format&fit=crop&q=80",
    previewImage: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&auto=format&fit=crop&q=80",
    isFeatured: true,
    viewsCount: 2150,
    usageCount: 135,
    version: 1,
    status: "PUBLISHED",
    supportedFeatures: ["whatsapp_checkout", "responsive_catalog", "spec_sheets", "warranty_tracking"],
    productLayout: {
      columnsDesktop: 4,
      columnsMobile: 2,
      cardStyle: "modern",
      showQuickBuy: true,
      showWishlist: true,
      showRating: true,
      badgePosition: "top-right",
    },
    mobileSettings: {
      stickyBottomNav: true,
      compactHeader: true,
      gridColumns: 2,
    },
    themeConfig: {
      style: "electronics",
      colors: {
        primary: "#2563EB",
        secondary: "#0284C7",
        accent: "#10B981",
        background: "#0B1120",
        surface: "#1E293B",
        text: "#F8FAFC",
        mutedText: "#94A3B8",
        headerBg: "#0F172A",
        footerBg: "#020617",
        footerText: "#94A3B8",
      },
      fonts: {
        heading: "Inter",
        body: "Inter",
      },
      borderRadius: "md",
      headerLayout: "standard",
      showAnnouncementBar: true,
      announcementText: "⚡ 100% GENUINE DEVICES WITH 1-YEAR OFFICIAL WARRANTY & FREE DELIVERY IN TOWN",
      announcementBg: "#2563EB",
      announcementTextColor: "#FFFFFF",
    },
    sections: [
      {
        id: "sec-hero",
        type: "hero",
        order: 1,
        visible: true,
        settings: { alignment: "left" },
        content: {
          badge: "ORIGINAL & VERIFIED GADGETS",
          headline: "Next-Generation Laptops, Phones & Audio",
          subheadline: "Genuine factory-sealed gadgets with verified manufacturer warranties, accessories, and instant tech support.",
          primaryCtaText: "Shop Flagship Devices",
          primaryCtaLink: "#products",
          secondaryCtaText: "View Deals",
          secondaryCtaLink: "#categories",
          imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200&auto=format&fit=crop&q=80",
          stats: [
            { label: "Devices In Stock", value: "500+" },
            { label: "Verified Brands", value: "30+" },
            { label: "Warranty Guarantee", value: "1 Year" },
          ],
        },
      },
      {
        id: "sec-categories",
        type: "categories",
        order: 2,
        visible: true,
        settings: {},
        content: {
          title: "Browse By Tech Category",
          subtitle: "Find the exact gear and accessories for your home and office",
          categories: [
            { name: "Smartphones & Tablets", count: "80 items", image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop&q=80" },
            { name: "Laptops & Workstations", count: "45 items", image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&auto=format&fit=crop&q=80" },
            { name: "Studio Audio & Headsets", count: "60 items", image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=80" },
            { name: "Smart Wearables", count: "35 items", image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop&q=80" },
          ],
        },
      },
      {
        id: "sec-products",
        type: "product-grid",
        order: 3,
        visible: true,
        settings: { limit: 8, columns: 4 },
        content: {
          title: "Bestselling Tech",
          subtitle: "Top-rated smartphones, audio gear, and laptops tested for quality",
        },
      },
      {
        id: "sec-faq",
        type: "faq",
        order: 4,
        visible: true,
        settings: {},
        content: {
          title: "Frequently Asked Questions",
          subtitle: "Everything you need to know about purchasing gadgets from us",
          faqs: [
            { question: "Are your gadgets 100% brand new and genuine?", answer: "Yes, all devices are brand new in original sealed boxes directly from authorized distributors." },
            { question: "Do you offer warranty?", answer: "Every smartphone and laptop includes a full 1-year replacement or repair warranty against manufacturing defects." },
            { question: "Can I pay Cash on Delivery?", answer: "Yes! We accept cash upon inspection at delivery within our service areas." },
          ],
        },
      },
    ],
  },

  // 5. ElectroMax
  {
    id: "tpl-electromax",
    templateId: "tpl-electromax",
    name: "ElectroMax",
    slug: "electromax",
    category: "Electronics & Tech",
    description: "High-energy electronics superstore with flash deals, mega banners, and multi-category layout for large catalogs.",
    tags: ["electronics", "appliances", "tv", "flash deals", "superstore"],
    style: "modern",
    thumbnail: "https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=800&auto=format&fit=crop&q=80",
    previewImage: "https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=1200&auto=format&fit=crop&q=80",
    isFeatured: false,
    viewsCount: 750,
    usageCount: 38,
    version: 1,
    status: "PUBLISHED",
    supportedFeatures: ["whatsapp_checkout", "responsive_catalog", "flash_deals"],
    productLayout: {
      columnsDesktop: 4,
      columnsMobile: 2,
      cardStyle: "modern",
      showQuickBuy: true,
      showWishlist: true,
      showRating: true,
      badgePosition: "top-left",
    },
    mobileSettings: {
      stickyBottomNav: true,
      compactHeader: true,
      gridColumns: 2,
    },
    themeConfig: {
      style: "modern",
      colors: {
        primary: "#0284C7",
        secondary: "#0369A1",
        accent: "#F97316",
        background: "#FFFFFF",
        surface: "#F0F9FF",
        text: "#0F172A",
        mutedText: "#64748B",
        headerBg: "#FFFFFF",
        footerBg: "#0F172A",
        footerText: "#F8FAFC",
      },
      fonts: {
        heading: "Inter",
        body: "Inter",
      },
      borderRadius: "lg",
      headerLayout: "standard",
      showAnnouncementBar: true,
      announcementText: "🔥 MEGA APPLIANCES SALE: Smart TVs, Refrigerators & AC Units on Discount!",
      announcementBg: "#0284C7",
      announcementTextColor: "#FFFFFF",
    },
    sections: [
      {
        id: "sec-hero",
        type: "hero",
        order: 1,
        visible: true,
        settings: { alignment: "left" },
        content: {
          badge: "SUPERSTORE DISCOUNTS",
          headline: "Smart Electronics for Every Home & Office",
          subheadline: "Upgrade your space with cutting-edge electronics, home entertainment systems, and heavy-duty smart appliances.",
          primaryCtaText: "Shop Electronics",
          primaryCtaLink: "#products",
          imageUrl: "https://images.unsplash.com/photo-1526738549149-8e07eca6c147?w=1200&auto=format&fit=crop&q=80",
        },
      },
      {
        id: "sec-products",
        type: "product-grid",
        order: 2,
        visible: true,
        settings: { limit: 8, columns: 4 },
        content: {
          title: "Flash Deals & Bestsellers",
          subtitle: "Top appliances with verified performance and local service guarantee",
        },
      },
    ],
  },

  // 6. FreshMart Express
  {
    id: "tpl-freshmart",
    templateId: "tpl-freshmart",
    name: "FreshMart Express",
    slug: "freshmart-express",
    category: "Supermarket & Grocery",
    description: "Vibrant grocery and fresh food market with produce categories, pantry staples, and rapid 2-hour grocery delivery badges.",
    tags: ["grocery", "supermarket", "fresh food", "produce", "organic"],
    style: "grocery",
    thumbnail: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&auto=format&fit=crop&q=80",
    previewImage: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&auto=format&fit=crop&q=80",
    isFeatured: true,
    viewsCount: 1680,
    usageCount: 95,
    version: 1,
    status: "PUBLISHED",
    supportedFeatures: ["whatsapp_checkout", "responsive_catalog", "express_delivery", "repeat_orders"],
    productLayout: {
      columnsDesktop: 4,
      columnsMobile: 2,
      cardStyle: "modern",
      showQuickBuy: true,
      showWishlist: false,
      showRating: true,
      badgePosition: "top-left",
    },
    mobileSettings: {
      stickyBottomNav: true,
      compactHeader: true,
      gridColumns: 2,
    },
    themeConfig: {
      style: "grocery",
      colors: {
        primary: "#16A34A",
        secondary: "#15803D",
        accent: "#EA580C",
        background: "#FFFFFF",
        surface: "#F0FDF4",
        text: "#14532D",
        mutedText: "#166534",
        headerBg: "#FFFFFF",
        footerBg: "#14532D",
        footerText: "#F0FDF4",
      },
      fonts: {
        heading: "Plus Jakarta Sans",
        body: "Inter",
      },
      borderRadius: "xl",
      headerLayout: "standard",
      showAnnouncementBar: true,
      announcementText: "🥬 FARM FRESH HARVEST: Order before 11am for same-day afternoon doorstep delivery!",
      announcementBg: "#16A34A",
      announcementTextColor: "#FFFFFF",
    },
    sections: [
      {
        id: "sec-hero",
        type: "hero",
        order: 1,
        visible: true,
        settings: { alignment: "left" },
        content: {
          badge: "FARM FRESH QUALITY",
          headline: "Farm-Fresh Groceries Delivered in Hours",
          subheadline: "Crisp vegetables, juicy fruits, grain essentials, cooking oils, and daily beverages sourced directly from trusted farmers.",
          primaryCtaText: "Order Daily Groceries",
          primaryCtaLink: "#products",
          imageUrl: "https://images.unsplash.com/photo-1610348725531-843dff563e2c?w=1200&auto=format&fit=crop&q=80",
          stats: [
            { label: "Fresh Items", value: "300+" },
            { label: "Local Farms", value: "25+" },
            { label: "Delivery Speed", value: "2 Hours" },
          ],
        },
      },
      {
        id: "sec-categories",
        type: "categories",
        order: 2,
        visible: true,
        settings: {},
        content: {
          title: "Fresh Aisles",
          subtitle: "Explore our daily stocked pantry and farm produce",
          categories: [
            { name: "Fresh Fruits & Veggies", count: "65 items", image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80" },
            { name: "Pantry & Grains", count: "90 items", image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80" },
            { name: "Dairy & Eggs", count: "30 items", image: "https://images.unsplash.com/photo-1528750997573-59b89d56f4f7?w=600&auto=format&fit=crop&q=80" },
            { name: "Beverages & Juices", count: "45 items", image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80" },
          ],
        },
      },
      {
        id: "sec-products",
        type: "product-grid",
        order: 3,
        visible: true,
        settings: { limit: 8, columns: 4 },
        content: {
          title: "Daily Kitchen Essentials",
          subtitle: "High demand grocery favorites at true wholesale community prices",
        },
      },
    ],
  },

  // 7. DailyBasket
  {
    id: "tpl-dailybasket",
    templateId: "tpl-dailybasket",
    name: "DailyBasket",
    slug: "dailybasket",
    category: "Supermarket & Grocery",
    description: "Clean and family-friendly pantry market design with recipe bundles, bulk provisions, and easy repeat re-ordering.",
    tags: ["grocery", "pantry", "household", "foodstuff", "provisions"],
    style: "clean",
    thumbnail: "https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800&auto=format&fit=crop&q=80",
    previewImage: "https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=1200&auto=format&fit=crop&q=80",
    isFeatured: false,
    viewsCount: 620,
    usageCount: 31,
    version: 1,
    status: "PUBLISHED",
    supportedFeatures: ["whatsapp_checkout", "responsive_catalog", "bulk_discounts"],
    productLayout: {
      columnsDesktop: 4,
      columnsMobile: 2,
      cardStyle: "bordered",
      showQuickBuy: true,
      showWishlist: false,
      showRating: true,
      badgePosition: "top-left",
    },
    mobileSettings: {
      stickyBottomNav: true,
      compactHeader: true,
      gridColumns: 2,
    },
    themeConfig: {
      style: "clean",
      colors: {
        primary: "#059669",
        secondary: "#10B981",
        accent: "#F59E0B",
        background: "#FFFFFF",
        surface: "#F9FAFB",
        text: "#111827",
        mutedText: "#4B5563",
        headerBg: "#FFFFFF",
        footerBg: "#111827",
        footerText: "#F3F4F6",
      },
      fonts: {
        heading: "Inter",
        body: "Inter",
      },
      borderRadius: "md",
      headerLayout: "standard",
      showAnnouncementBar: true,
      announcementText: "📦 STOCK YOUR PANTRY: Free delivery on 25kg and 50kg rice bags nationwide!",
      announcementBg: "#059669",
      announcementTextColor: "#FFFFFF",
    },
    sections: [
      {
        id: "sec-hero",
        type: "hero",
        order: 1,
        visible: true,
        settings: { alignment: "left" },
        content: {
          badge: "EVERYDAY LOW PRICES",
          headline: "Your Household Pantry & Food Basket",
          subheadline: "Quality rice, cooking oils, flour, seasoning, and household supplies packed and delivered to your doorstep.",
          primaryCtaText: "Fill Your Basket",
          primaryCtaLink: "#products",
          imageUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&auto=format&fit=crop&q=80",
        },
      },
      {
        id: "sec-products",
        type: "product-grid",
        order: 2,
        visible: true,
        settings: { limit: 8, columns: 4 },
        content: {
          title: "Popular Pantry Items",
          subtitle: "Essential provisions every home needs at fair prices",
        },
      },
    ],
  },

  // 8. BeautyGlow
  {
    id: "tpl-beautyglow",
    templateId: "tpl-beautyglow",
    name: "BeautyGlow",
    slug: "beautyglow",
    category: "Beauty & Cosmetics",
    description: "Soft rose aesthetic with skincare routines, ingredient spotlights, customer shade matching, and dermatologist badges.",
    tags: ["beauty", "cosmetics", "skincare", "makeup", "haircare"],
    style: "beauty",
    thumbnail: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80",
    previewImage: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=1200&auto=format&fit=crop&q=80",
    isFeatured: true,
    viewsCount: 1540,
    usageCount: 89,
    version: 1,
    status: "PUBLISHED",
    supportedFeatures: ["whatsapp_checkout", "responsive_catalog", "shade_finder", "ingredient_highlights"],
    productLayout: {
      columnsDesktop: 4,
      columnsMobile: 2,
      cardStyle: "modern",
      showQuickBuy: true,
      showWishlist: true,
      showRating: true,
      badgePosition: "top-right",
    },
    mobileSettings: {
      stickyBottomNav: true,
      compactHeader: true,
      gridColumns: 2,
    },
    themeConfig: {
      style: "beauty",
      colors: {
        primary: "#DB2777",
        secondary: "#BE185D",
        accent: "#F472B6",
        background: "#FFFDFD",
        surface: "#FDF2F8",
        text: "#831843",
        mutedText: "#9D174D",
        headerBg: "#FFFFFF",
        footerBg: "#500724",
        footerText: "#FCE7F3",
      },
      fonts: {
        heading: "Playfair Display",
        body: "Inter",
      },
      borderRadius: "xl",
      headerLayout: "standard",
      showAnnouncementBar: true,
      announcementText: "🌸 100% AUTHENTIC SKINCARE & MAKEUP — DERMATOLOGIST TESTED FOR RADIANT SKIN",
      announcementBg: "#DB2777",
      announcementTextColor: "#FFFFFF",
    },
    sections: [
      {
        id: "sec-hero",
        type: "hero",
        order: 1,
        visible: true,
        settings: { alignment: "left" },
        content: {
          badge: "CLEAN & GENTLE BEAUTY",
          headline: "Illuminate Your Skin's Natural Radiance",
          subheadline: "Formulations crafted with certified organic botanicals, hydrating serums, and vibrant cosmetics for flawless tone.",
          primaryCtaText: "Discover Skincare",
          primaryCtaLink: "#products",
          imageUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=1200&auto=format&fit=crop&q=80",
        },
      },
      {
        id: "sec-products",
        type: "product-grid",
        order: 2,
        visible: true,
        settings: { limit: 8, columns: 4 },
        content: {
          title: "Bestselling Beauty Essentials",
          subtitle: "Top rated serums, moisturisers, lipsticks and glowing body lotions",
        },
      },
      {
        id: "sec-testimonials",
        type: "testimonials",
        order: 3,
        visible: true,
        settings: {},
        content: {
          title: "What Our Customers Say",
          subtitle: "Real results from people who transformed their skincare routine",
          testimonials: [
            { name: "Mariama S.", role: "Beauty Creator", comment: "The glow oil worked wonders on my hyperpigmentation. Original products and super fast delivery!", rating: 5 },
            { name: "Aminata C.", role: "Bride", comment: "Bought my complete wedding makeup kit here. The shade match was spot on!", rating: 5 },
          ],
        },
      },
    ],
  },

  // 9. Elegance Cosmetics
  {
    id: "tpl-elegance",
    templateId: "tpl-elegance",
    name: "Elegance Cosmetics",
    slug: "elegance-cosmetics",
    category: "Beauty & Cosmetics",
    description: "Refined, high-end luxury beauty layout tailored for perfumes, designer colognes, and luxury skincare lines.",
    tags: ["perfume", "cologne", "luxury beauty", "fragrances", "skincare"],
    style: "luxury",
    thumbnail: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&auto=format&fit=crop&q=80",
    previewImage: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=1200&auto=format&fit=crop&q=80",
    isFeatured: false,
    viewsCount: 680,
    usageCount: 34,
    version: 1,
    status: "PUBLISHED",
    supportedFeatures: ["whatsapp_checkout", "responsive_catalog", "fragrance_notes"],
    productLayout: {
      columnsDesktop: 3,
      columnsMobile: 1,
      cardStyle: "elevated",
      showQuickBuy: true,
      showWishlist: true,
      showRating: false,
      badgePosition: "top-right",
    },
    mobileSettings: {
      stickyBottomNav: true,
      compactHeader: false,
      gridColumns: 1,
    },
    themeConfig: {
      style: "luxury",
      colors: {
        primary: "#C084FC",
        secondary: "#A855F7",
        accent: "#F472B6",
        background: "#09090B",
        surface: "#18181B",
        text: "#FAF5FF",
        mutedText: "#C4B5FD",
        headerBg: "#09090B",
        footerBg: "#040405",
        footerText: "#E9D5FF",
      },
      fonts: {
        heading: "Playfair Display",
        body: "Inter",
      },
      borderRadius: "none",
      headerLayout: "centered",
      showAnnouncementBar: true,
      announcementText: "✨ BESPOKE FRENCH & ARABIAN OUD FRAGRANCES — COMPLIMENTARY GIFT WRAPPING",
      announcementBg: "#A855F7",
      announcementTextColor: "#000000",
    },
    sections: [
      {
        id: "sec-hero",
        type: "hero",
        order: 1,
        visible: true,
        settings: { alignment: "center" },
        content: {
          badge: "HAUTE PARFUMERIE",
          headline: "Scents That Leave an Unforgettable Memory",
          subheadline: "Rare extrait de parfums, pure oud oils, and captivating aromas formulated by renowned master perfumers.",
          primaryCtaText: "Explore Fragrances",
          primaryCtaLink: "#products",
          imageUrl: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=1200&auto=format&fit=crop&q=80",
        },
      },
      {
        id: "sec-products",
        type: "product-grid",
        order: 2,
        visible: true,
        settings: { limit: 6, columns: 3 },
        content: {
          title: "The Fragrance Atelier",
          subtitle: "Exquisite scents curated for evening galas and distinguished presence",
        },
      },
    ],
  },

  // 10. MediCare Pharmacy
  {
    id: "tpl-medicare",
    templateId: "tpl-medicare",
    name: "MediCare Pharmacy",
    slug: "medicare-pharmacy",
    category: "Health & Pharmacy",
    description: "Trusted medical and health storefront with prescription upload banner, vitamins catalog, and pharmacist consultation button.",
    tags: ["pharmacy", "health", "medicine", "vitamins", "first aid", "wellness"],
    style: "pharmacy",
    thumbnail: "https://images.unsplash.com/photo-1586015555751-63c29571e467?w=800&auto=format&fit=crop&q=80",
    previewImage: "https://images.unsplash.com/photo-1586015555751-63c29571e467?w=1200&auto=format&fit=crop&q=80",
    isFeatured: true,
    viewsCount: 1320,
    usageCount: 71,
    version: 1,
    status: "PUBLISHED",
    supportedFeatures: ["whatsapp_checkout", "responsive_catalog", "prescription_upload", "pharmacist_chat"],
    productLayout: {
      columnsDesktop: 4,
      columnsMobile: 2,
      cardStyle: "modern",
      showQuickBuy: true,
      showWishlist: false,
      showRating: false,
      badgePosition: "top-left",
    },
    mobileSettings: {
      stickyBottomNav: true,
      compactHeader: true,
      gridColumns: 2,
    },
    themeConfig: {
      style: "pharmacy",
      colors: {
        primary: "#0D9488",
        secondary: "#0F766E",
        accent: "#0284C7",
        background: "#FFFFFF",
        surface: "#F0FDFA",
        text: "#134E4A",
        mutedText: "#115E59",
        headerBg: "#FFFFFF",
        footerBg: "#134E4A",
        footerText: "#F0FDFA",
      },
      fonts: {
        heading: "Inter",
        body: "Inter",
      },
      borderRadius: "lg",
      headerLayout: "standard",
      showAnnouncementBar: true,
      announcementText: "💊 LICENSED PHARMACIST ON DUTY: Fast discrete prescription delivery across town",
      announcementBg: "#0D9488",
      announcementTextColor: "#FFFFFF",
    },
    sections: [
      {
        id: "sec-hero",
        type: "hero",
        order: 1,
        visible: true,
        settings: { alignment: "left" },
        content: {
          badge: "REGISTERED & LICENSED PHARMACY",
          headline: "Essential Medicines & Family Healthcare at Home",
          subheadline: "Authentic pharmaceuticals, vitamins, supplements, maternal health supplies, and diagnostic tools delivered with utmost care.",
          primaryCtaText: "Shop Healthcare",
          primaryCtaLink: "#products",
          secondaryCtaText: "Chat with Pharmacist",
          secondaryCtaLink: "#contact",
          imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=1200&auto=format&fit=crop&q=80",
        },
      },
      {
        id: "sec-products",
        type: "product-grid",
        order: 2,
        visible: true,
        settings: { limit: 8, columns: 4 },
        content: {
          title: "Over-The-Counter & Wellness",
          subtitle: "Essential first aid, vitamins, supplements, and family hygiene items",
        },
      },
      {
        id: "sec-faq",
        type: "faq",
        order: 3,
        visible: true,
        settings: {},
        content: {
          title: "Pharmacy FAQ",
          subtitle: "Clear answers on medicine orders and dosage advice",
          faqs: [
            { question: "How do I send my doctor's prescription?", answer: "Take a clear picture and send it directly to our WhatsApp pharmacist number for immediate verification." },
            { question: "Are your medicines genuine and stored at correct temperatures?", answer: "Yes, our facility operates temperature-controlled storage complying with all national pharmacy board regulations." },
          ],
        },
      },
    ],
  },

  // 11. FoodHouse Bistro
  {
    id: "tpl-foodhouse",
    templateId: "tpl-foodhouse",
    name: "FoodHouse Bistro",
    slug: "foodhouse-bistro",
    category: "Food & Restaurant",
    description: "Appetizing warm restaurant layout with menu tabs, chef specials, online takeaway ordering, and hot food delivery alerts.",
    tags: ["restaurant", "food", "dining", "takeaway", "bistro", "catering"],
    style: "restaurant",
    thumbnail: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80",
    previewImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&auto=format&fit=crop&q=80",
    isFeatured: true,
    viewsCount: 1480,
    usageCount: 82,
    version: 1,
    status: "PUBLISHED",
    supportedFeatures: ["whatsapp_checkout", "responsive_catalog", "instant_takeaway", "hot_food_timer"],
    productLayout: {
      columnsDesktop: 3,
      columnsMobile: 1,
      cardStyle: "modern",
      showQuickBuy: true,
      showWishlist: false,
      showRating: true,
      badgePosition: "top-left",
    },
    mobileSettings: {
      stickyBottomNav: true,
      compactHeader: true,
      gridColumns: 1,
    },
    themeConfig: {
      style: "restaurant",
      colors: {
        primary: "#EA580C",
        secondary: "#C2410C",
        accent: "#FBBF24",
        background: "#0C0A09",
        surface: "#1C1917",
        text: "#FAFAF9",
        mutedText: "#A8A29E",
        headerBg: "#0C0A09",
        footerBg: "#000000",
        footerText: "#D6D3D1",
      },
      fonts: {
        heading: "Playfair Display",
        body: "Inter",
      },
      borderRadius: "xl",
      headerLayout: "standard",
      showAnnouncementBar: true,
      announcementText: "🔥 FRESH FROM THE GRILL: Hot lunch & dinner delivered in 30-45 minutes!",
      announcementBg: "#EA580C",
      announcementTextColor: "#FFFFFF",
    },
    sections: [
      {
        id: "sec-hero",
        type: "hero",
        order: 1,
        visible: true,
        settings: { alignment: "left" },
        content: {
          badge: "SIZZLING & FLAVORFUL",
          headline: "Gourmet Cuisine & Comfort Meals Delivered Hot",
          subheadline: "From spicy Jollof rice and grilled fish to succulent steaks and fresh salads, savor delicious culinary excellence.",
          primaryCtaText: "Order Hot Food Now",
          primaryCtaLink: "#products",
          imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&auto=format&fit=crop&q=80",
        },
      },
      {
        id: "sec-products",
        type: "product-grid",
        order: 2,
        visible: true,
        settings: { limit: 6, columns: 3 },
        content: {
          title: "Chef's Specials & Popular Dishes",
          subtitle: "Freshly prepared with authentic herbs and premium spices",
        },
      },
    ],
  },

  // 12. TasteHub Kitchen
  {
    id: "tpl-tastehub",
    templateId: "tpl-tastehub",
    name: "TasteHub Kitchen",
    slug: "tastehub-kitchen",
    category: "Food & Restaurant",
    description: "Fast-casual dining design featuring combo platters, family feasts, party catering bookings, and WhatsApp instant takeout.",
    tags: ["food", "takeout", "burger", "pizza", "fried chicken", "combos"],
    style: "vibrant",
    thumbnail: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&auto=format&fit=crop&q=80",
    previewImage: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1200&auto=format&fit=crop&q=80",
    isFeatured: false,
    viewsCount: 710,
    usageCount: 39,
    version: 1,
    status: "PUBLISHED",
    supportedFeatures: ["whatsapp_checkout", "responsive_catalog", "combo_builder"],
    productLayout: {
      columnsDesktop: 3,
      columnsMobile: 1,
      cardStyle: "modern",
      showQuickBuy: true,
      showWishlist: false,
      showRating: true,
      badgePosition: "top-left",
    },
    mobileSettings: {
      stickyBottomNav: true,
      compactHeader: true,
      gridColumns: 1,
    },
    themeConfig: {
      style: "vibrant",
      colors: {
        primary: "#DC2626",
        secondary: "#B91C1C",
        accent: "#FBBF24",
        background: "#FFFFFF",
        surface: "#FEF2F2",
        text: "#1F2937",
        mutedText: "#4B5563",
        headerBg: "#FFFFFF",
        footerBg: "#1F2937",
        footerText: "#F9FAFB",
      },
      fonts: {
        heading: "Plus Jakarta Sans",
        body: "Inter",
      },
      borderRadius: "lg",
      headerLayout: "standard",
      showAnnouncementBar: true,
      announcementText: "🍔 FAMILY FEAST DEAL: Get 2 free drinks with any Large Platter ordered today!",
      announcementBg: "#DC2626",
      announcementTextColor: "#FFFFFF",
    },
    sections: [
      {
        id: "sec-hero",
        type: "hero",
        order: 1,
        visible: true,
        settings: { alignment: "left" },
        content: {
          badge: "FAST, FRESH & CRISPY",
          headline: "Delicious Fast Bites & Family Feasts",
          subheadline: "Crispy golden fried chicken, loaded burgers, freshly baked pizzas, and cold beverages delivered straight to your door.",
          primaryCtaText: "Order Delivery",
          primaryCtaLink: "#products",
          imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=1200&auto=format&fit=crop&q=80",
        },
      },
      {
        id: "sec-products",
        type: "product-grid",
        order: 2,
        visible: true,
        settings: { limit: 6, columns: 3 },
        content: {
          title: "Popular Feasts & Combos",
          subtitle: "Hearty portions made fresh to order",
        },
      },
    ],
  },

  // 13. BuildPro Hardware
  {
    id: "tpl-buildpro",
    templateId: "tpl-buildpro",
    name: "BuildPro Hardware",
    slug: "buildpro-hardware",
    category: "Automotive & Hardware",
    description: "Industrial heavy-duty hardware and building supplies catalog with bulk quote requests, contractor pricing, and site delivery.",
    tags: ["hardware", "tools", "building materials", "cement", "construction", "industrial"],
    style: "industrial",
    thumbnail: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80",
    previewImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&auto=format&fit=crop&q=80",
    isFeatured: true,
    viewsCount: 960,
    usageCount: 52,
    version: 1,
    status: "PUBLISHED",
    supportedFeatures: ["whatsapp_checkout", "responsive_catalog", "bulk_inquiry", "truck_delivery"],
    productLayout: {
      columnsDesktop: 4,
      columnsMobile: 2,
      cardStyle: "bordered",
      showQuickBuy: true,
      showWishlist: true,
      showRating: false,
      badgePosition: "top-left",
    },
    mobileSettings: {
      stickyBottomNav: true,
      compactHeader: true,
      gridColumns: 2,
    },
    themeConfig: {
      style: "industrial",
      colors: {
        primary: "#D97706",
        secondary: "#B45309",
        accent: "#F59E0B",
        background: "#FFFFFF",
        surface: "#FFFBEB",
        text: "#1F2937",
        mutedText: "#4B5563",
        headerBg: "#1F2937",
        footerBg: "#111827",
        footerText: "#F3F4F6",
      },
      fonts: {
        heading: "Inter",
        body: "Inter",
      },
      borderRadius: "sm",
      headerLayout: "standard",
      showAnnouncementBar: true,
      announcementText: "🏗️ CONTRACTOR WHOLESALE: Direct site delivery for cement, steel rods, paints and power tools",
      announcementBg: "#D97706",
      announcementTextColor: "#000000",
    },
    sections: [
      {
        id: "sec-hero",
        type: "hero",
        order: 1,
        visible: true,
        settings: { alignment: "left" },
        content: {
          badge: "CERTIFIED INDUSTRIAL GRADE",
          headline: "Professional Building Materials & Heavy Power Tools",
          subheadline: "Equip your construction sites and renovation projects with certified cement, iron rods, electricals, plumbing, and professional tools.",
          primaryCtaText: "Browse Building Supplies",
          primaryCtaLink: "#products",
          secondaryCtaText: "Request Bulk Quote",
          secondaryCtaLink: "#contact",
          imageUrl: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=1200&auto=format&fit=crop&q=80",
        },
      },
      {
        id: "sec-products",
        type: "product-grid",
        order: 2,
        visible: true,
        settings: { limit: 8, columns: 4 },
        content: {
          title: "Top Building Supplies & Hardware",
          subtitle: "Tested, durable, and ready for commercial construction dispatch",
        },
      },
    ],
  },

  // 14. HomeStyle Living
  {
    id: "tpl-homestyle",
    templateId: "tpl-homestyle",
    name: "HomeStyle Living",
    slug: "homestyle-living",
    category: "Home & Furniture",
    description: "Serene, minimalist home decor and furniture showcase with room inspiration galleries, dimension tags, and assemble services.",
    tags: ["furniture", "decor", "home", "interior", "living room", "minimalist"],
    style: "minimalist",
    thumbnail: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80",
    previewImage: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&auto=format&fit=crop&q=80",
    isFeatured: true,
    viewsCount: 1120,
    usageCount: 65,
    version: 1,
    status: "PUBLISHED",
    supportedFeatures: ["whatsapp_checkout", "responsive_catalog", "room_planner", "assembly_service"],
    productLayout: {
      columnsDesktop: 3,
      columnsMobile: 1,
      cardStyle: "modern",
      showQuickBuy: true,
      showWishlist: true,
      showRating: true,
      badgePosition: "top-right",
    },
    mobileSettings: {
      stickyBottomNav: true,
      compactHeader: true,
      gridColumns: 1,
    },
    themeConfig: {
      style: "minimalist",
      colors: {
        primary: "#78350F",
        secondary: "#92400E",
        accent: "#D97706",
        background: "#FDFCFA",
        surface: "#F7F3EE",
        text: "#292524",
        mutedText: "#57534E",
        headerBg: "#FDFCFA",
        footerBg: "#292524",
        footerText: "#F5F5F4",
      },
      fonts: {
        heading: "Playfair Display",
        body: "Inter",
      },
      borderRadius: "lg",
      headerLayout: "centered",
      showAnnouncementBar: true,
      announcementText: "🛋️ FREE IN-HOME ASSEMBLY & ROOM PLACEMENT ON ALL LIVING ROOM SETS",
      announcementBg: "#78350F",
      announcementTextColor: "#FFFFFF",
    },
    sections: [
      {
        id: "sec-hero",
        type: "hero",
        order: 1,
        visible: true,
        settings: { alignment: "center" },
        content: {
          badge: "CONTEMPORARY INTERIORS",
          headline: "Crafting Spaces of Comfort and Serenity",
          subheadline: "Solid hardwood dining sets, plush sofas, ergonomic workstations, and bespoke modern decor for graceful living.",
          primaryCtaText: "Explore Furniture",
          primaryCtaLink: "#products",
          imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1200&auto=format&fit=crop&q=80",
        },
      },
      {
        id: "sec-products",
        type: "product-grid",
        order: 2,
        visible: true,
        settings: { limit: 6, columns: 3 },
        content: {
          title: "Signature Living Pieces",
          subtitle: "Elegantly constructed furniture designed for lasting beauty",
        },
      },
    ],
  },

  // 15. Royal Jewels
  {
    id: "tpl-royaljewels",
    templateId: "tpl-royaljewels",
    name: "Royal Jewels",
    slug: "royal-jewels",
    category: "Jewelry & Luxury",
    description: "Opulent gold and gem showcase with certified authenticity seals, ring sizers, gift boxing, and private consultation flows.",
    tags: ["jewelry", "gold", "diamonds", "watches", "rings", "luxury"],
    style: "luxury",
    thumbnail: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&auto=format&fit=crop&q=80",
    previewImage: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=1200&auto=format&fit=crop&q=80",
    isFeatured: true,
    viewsCount: 1390,
    usageCount: 78,
    version: 1,
    status: "PUBLISHED",
    supportedFeatures: ["whatsapp_checkout", "responsive_catalog", "ring_sizer", "certificate_verification"],
    productLayout: {
      columnsDesktop: 3,
      columnsMobile: 1,
      cardStyle: "elevated",
      showQuickBuy: true,
      showWishlist: true,
      showRating: false,
      badgePosition: "top-right",
    },
    mobileSettings: {
      stickyBottomNav: true,
      compactHeader: false,
      gridColumns: 1,
    },
    themeConfig: {
      style: "luxury",
      colors: {
        primary: "#F59E0B",
        secondary: "#D97706",
        accent: "#FBBF24",
        background: "#030712",
        surface: "#111827",
        text: "#F9FAFB",
        mutedText: "#9CA3AF",
        headerBg: "#030712",
        footerBg: "#000000",
        footerText: "#E5E7EB",
      },
      fonts: {
        heading: "Playfair Display",
        body: "Cinzel",
      },
      borderRadius: "none",
      headerLayout: "centered",
      showAnnouncementBar: true,
      announcementText: "💎 CERTIFIED 18K & 24K GOLD JEWELRY WITH LIFETIME POLISHING & AUTHENTICITY PAPERS",
      announcementBg: "#F59E0B",
      announcementTextColor: "#000000",
    },
    sections: [
      {
        id: "sec-hero",
        type: "hero",
        order: 1,
        visible: true,
        settings: { alignment: "center" },
        content: {
          badge: "TIMELESS BRILLIANCE",
          headline: "Exquisite Gold, Fine Gems & Heirloom Jewels",
          subheadline: "Celebrated for masterful cuts, genuine Sierra Leonean gemstones, and breathtaking bridal and anniversary sets.",
          primaryCtaText: "View Fine Jewelry",
          primaryCtaLink: "#products",
          imageUrl: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=1200&auto=format&fit=crop&q=80",
        },
      },
      {
        id: "sec-products",
        type: "product-grid",
        order: 2,
        visible: true,
        settings: { limit: 6, columns: 3 },
        content: {
          title: "Masterpiece Collections",
          subtitle: "Radiant rings, necklaces, bracelets, and handcrafted luxury timepieces",
        },
      },
    ],
  },

  // 16. AutoZone Parts
  {
    id: "tpl-autozone",
    templateId: "tpl-autozone",
    name: "AutoZone Parts",
    slug: "autozone-parts",
    category: "Automotive & Hardware",
    description: "High-octane automotive parts, tires, oils, batteries, and diagnostic accessories storefront with instant WhatsApp order hotline.",
    tags: ["auto", "car parts", "tires", "batteries", "mechanic", "automotive"],
    style: "bold",
    thumbnail: "https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=800&auto=format&fit=crop&q=80",
    previewImage: "https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=1200&auto=format&fit=crop&q=80",
    isFeatured: false,
    viewsCount: 640,
    usageCount: 29,
    version: 1,
    status: "PUBLISHED",
    supportedFeatures: ["whatsapp_checkout", "responsive_catalog", "part_finder"],
    productLayout: {
      columnsDesktop: 4,
      columnsMobile: 2,
      cardStyle: "bordered",
      showQuickBuy: true,
      showWishlist: true,
      showRating: true,
      badgePosition: "top-left",
    },
    mobileSettings: {
      stickyBottomNav: true,
      compactHeader: true,
      gridColumns: 2,
    },
    themeConfig: {
      style: "bold",
      colors: {
        primary: "#DC2626",
        secondary: "#B91C1C",
        accent: "#F59E0B",
        background: "#0F172A",
        surface: "#1E293B",
        text: "#F8FAFC",
        mutedText: "#94A3B8",
        headerBg: "#0F172A",
        footerBg: "#020617",
        footerText: "#94A3B8",
      },
      fonts: {
        heading: "Inter",
        body: "Inter",
      },
      borderRadius: "md",
      headerLayout: "standard",
      showAnnouncementBar: true,
      announcementText: "🚗 GENUINE TOYOTA, MERCEDES & NISSAN SPARES — SAME-DAY WORKSHOP DELIVERY",
      announcementBg: "#DC2626",
      announcementTextColor: "#FFFFFF",
    },
    sections: [
      {
        id: "sec-hero",
        type: "hero",
        order: 1,
        visible: true,
        settings: { alignment: "left" },
        content: {
          badge: "ORIGINAL OEM & AFTERMARKET",
          headline: "Keep Your Vehicle Moving at Peak Performance",
          subheadline: "Premium brake pads, filters, engine lubricants, shock absorbers, and heavy duty tires with guaranteed fitment.",
          primaryCtaText: "Find Spare Parts",
          primaryCtaLink: "#products",
          imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&auto=format&fit=crop&q=80",
        },
      },
      {
        id: "sec-products",
        type: "product-grid",
        order: 2,
        visible: true,
        settings: { limit: 8, columns: 4 },
        content: {
          title: "Essential Maintenance & Spares",
          subtitle: "Top-selling parts for reliable driving across any terrain",
        },
      },
    ],
  },

  // 17. PhoneWorld
  {
    id: "tpl-phoneworld",
    templateId: "tpl-phoneworld",
    name: "PhoneWorld",
    slug: "phoneworld",
    category: "Electronics & Tech",
    description: "Sleek mobile retail specialist theme designed for iPhone, Samsung, Tecno, Infinix, cases, screen guards, and trade-in promos.",
    tags: ["phones", "smartphones", "iphone", "samsung", "accessories", "mobile"],
    style: "modern",
    thumbnail: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80",
    previewImage: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200&auto=format&fit=crop&q=80",
    isFeatured: false,
    viewsCount: 820,
    usageCount: 45,
    version: 1,
    status: "PUBLISHED",
    supportedFeatures: ["whatsapp_checkout", "responsive_catalog", "trade_in_quote"],
    productLayout: {
      columnsDesktop: 4,
      columnsMobile: 2,
      cardStyle: "modern",
      showQuickBuy: true,
      showWishlist: true,
      showRating: true,
      badgePosition: "top-right",
    },
    mobileSettings: {
      stickyBottomNav: true,
      compactHeader: true,
      gridColumns: 2,
    },
    themeConfig: {
      style: "modern",
      colors: {
        primary: "#6366F1",
        secondary: "#4F46E5",
        accent: "#06B6D4",
        background: "#FFFFFF",
        surface: "#EEF2FF",
        text: "#1E1B4B",
        mutedText: "#4338CA",
        headerBg: "#FFFFFF",
        footerBg: "#1E1B4B",
        footerText: "#EEF2FF",
      },
      fonts: {
        heading: "Inter",
        body: "Inter",
      },
      borderRadius: "lg",
      headerLayout: "standard",
      showAnnouncementBar: true,
      announcementText: "📱 TRADE-IN YOUR OLD PHONE FOR THE LATEST MODEL — BEST VALUE GUARANTEED",
      announcementBg: "#6366F1",
      announcementTextColor: "#FFFFFF",
    },
    sections: [
      {
        id: "sec-hero",
        type: "hero",
        order: 1,
        visible: true,
        settings: { alignment: "left" },
        content: {
          badge: "LATEST FLAGSHIPS IN STOCK",
          headline: "The Latest Smartphones & Mobile Accessories",
          subheadline: "Factory unlocked iPhones, Galaxy flagships, budget-friendly smartphones, fast chargers, and premium cases.",
          primaryCtaText: "Explore Phones",
          primaryCtaLink: "#products",
          imageUrl: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=1200&auto=format&fit=crop&q=80",
        },
      },
      {
        id: "sec-products",
        type: "product-grid",
        order: 2,
        visible: true,
        settings: { limit: 8, columns: 4 },
        content: {
          title: "Featured Smartphones",
          subtitle: "Brand new sealed phones with guaranteed network unlocked support",
        },
      },
    ],
  },

  // 18. KidsWorld Toys
  {
    id: "tpl-kidsworld",
    templateId: "tpl-kidsworld",
    name: "KidsWorld Toys",
    slug: "kidsworld-toys",
    category: "Kids & Toys",
    description: "Bright, playful, child-safe toy and baby gear storefront with age filters, educational kits, and gift wrapping options.",
    tags: ["toys", "kids", "baby", "learning", "games", "playful"],
    style: "playful",
    thumbnail: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&auto=format&fit=crop&q=80",
    previewImage: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=1200&auto=format&fit=crop&q=80",
    isFeatured: false,
    viewsCount: 560,
    usageCount: 28,
    version: 1,
    status: "PUBLISHED",
    supportedFeatures: ["whatsapp_checkout", "responsive_catalog", "age_filter"],
    productLayout: {
      columnsDesktop: 4,
      columnsMobile: 2,
      cardStyle: "modern",
      showQuickBuy: true,
      showWishlist: true,
      showRating: true,
      badgePosition: "top-left",
    },
    mobileSettings: {
      stickyBottomNav: true,
      compactHeader: true,
      gridColumns: 2,
    },
    themeConfig: {
      style: "playful",
      colors: {
        primary: "#EC4899",
        secondary: "#8B5CF6",
        accent: "#FBBF24",
        background: "#FFFBEB",
        surface: "#FEF3C7",
        text: "#1E293B",
        mutedText: "#475569",
        headerBg: "#FFFFFF",
        footerBg: "#1E293B",
        footerText: "#F8FAFC",
      },
      fonts: {
        heading: "Plus Jakarta Sans",
        body: "Inter",
      },
      borderRadius: "xl",
      headerLayout: "standard",
      showAnnouncementBar: true,
      announcementText: "🎈 BIRTHDAY GIFT SPECIAL: Free gift wrapping & greeting card with every toy order!",
      announcementBg: "#EC4899",
      announcementTextColor: "#FFFFFF",
    },
    sections: [
      {
        id: "sec-hero",
        type: "hero",
        order: 1,
        visible: true,
        settings: { alignment: "left" },
        content: {
          badge: "SAFE & EDUCATIONAL TOYS",
          headline: "Spark Imagination, Wonder & Learning",
          subheadline: "Creative building blocks, STEM kits, soft plush dolls, outdoor games, and nursery essentials designed with love.",
          primaryCtaText: "Shop Kids Toys",
          primaryCtaLink: "#products",
          imageUrl: "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=1200&auto=format&fit=crop&q=80",
        },
      },
      {
        id: "sec-products",
        type: "product-grid",
        order: 2,
        visible: true,
        settings: { limit: 8, columns: 4 },
        content: {
          title: "Fun Favorites",
          subtitle: "Safe, durable toys kids of all ages adore",
        },
      },
    ],
  },

  // 19. SportsPro Athletics
  {
    id: "tpl-sportspro",
    templateId: "tpl-sportspro",
    name: "SportsPro Athletics",
    slug: "sportspro-athletics",
    category: "Sports & Outdoor",
    description: "High-octane sports gear, fitness equipment, gym wear, football kits, and outdoor athletic essentials store.",
    tags: ["sports", "fitness", "gym", "football", "athletics", "training"],
    style: "bold",
    thumbnail: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80",
    previewImage: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=1200&auto=format&fit=crop&q=80",
    isFeatured: true,
    viewsCount: 1040,
    usageCount: 56,
    version: 1,
    status: "PUBLISHED",
    supportedFeatures: ["whatsapp_checkout", "responsive_catalog", "size_guide"],
    productLayout: {
      columnsDesktop: 4,
      columnsMobile: 2,
      cardStyle: "modern",
      showQuickBuy: true,
      showWishlist: true,
      showRating: true,
      badgePosition: "top-left",
    },
    mobileSettings: {
      stickyBottomNav: true,
      compactHeader: true,
      gridColumns: 2,
    },
    themeConfig: {
      style: "bold",
      colors: {
        primary: "#10B981",
        secondary: "#059669",
        accent: "#F59E0B",
        background: "#090A0F",
        surface: "#121420",
        text: "#F8FAFC",
        mutedText: "#94A3B8",
        headerBg: "#090A0F",
        footerBg: "#030408",
        footerText: "#94A3B8",
      },
      fonts: {
        heading: "Inter",
        body: "Inter",
      },
      borderRadius: "md",
      headerLayout: "standard",
      showAnnouncementBar: true,
      announcementText: "⚡ UNLEASH YOUR POTENTIAL — ORIGINAL FOOTBALL KITS, RUNNING SHOES & GYM GEAR",
      announcementBg: "#10B981",
      announcementTextColor: "#000000",
    },
    sections: [
      {
        id: "sec-hero",
        type: "hero",
        order: 1,
        visible: true,
        settings: { alignment: "left" },
        content: {
          badge: "BUILT FOR CHAMPIONS",
          headline: "Gear Up With Professional Athletic Performance",
          subheadline: "Club football jerseys, endurance running footwear, dumbbells, yoga accessories, and breathable training gear.",
          primaryCtaText: "Shop Athletics",
          primaryCtaLink: "#products",
          imageUrl: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=1200&auto=format&fit=crop&q=80",
        },
      },
      {
        id: "sec-products",
        type: "product-grid",
        order: 2,
        visible: true,
        settings: { limit: 8, columns: 4 },
        content: {
          title: "Top Athletic Gear",
          subtitle: "Engineered for maximum endurance and everyday training comfort",
        },
      },
    ],
  },

  // 20. ProBusiness Elite
  {
    id: "tpl-probusiness",
    templateId: "tpl-probusiness",
    name: "ProBusiness Elite",
    slug: "probusiness-elite",
    category: "Corporate & Services",
    description: "Executive corporate services, consultancy packages, digital products, and professional business solutions hub.",
    tags: ["corporate", "services", "consulting", "business", "professional", "clean"],
    style: "clean",
    thumbnail: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80",
    previewImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80",
    isFeatured: true,
    viewsCount: 1250,
    usageCount: 62,
    version: 1,
    status: "PUBLISHED",
    supportedFeatures: ["whatsapp_checkout", "responsive_catalog", "inquiry_form", "appointment_booking"],
    productLayout: {
      columnsDesktop: 3,
      columnsMobile: 1,
      cardStyle: "elevated",
      showQuickBuy: true,
      showWishlist: false,
      showRating: false,
      badgePosition: "top-right",
    },
    mobileSettings: {
      stickyBottomNav: true,
      compactHeader: false,
      gridColumns: 1,
    },
    themeConfig: {
      style: "clean",
      colors: {
        primary: "#1E3A8A",
        secondary: "#1D4ED8",
        accent: "#F59E0B",
        background: "#FFFFFF",
        surface: "#F8FAFC",
        text: "#0F172A",
        mutedText: "#475569",
        headerBg: "#FFFFFF",
        footerBg: "#0F172A",
        footerText: "#F8FAFC",
      },
      fonts: {
        heading: "Plus Jakarta Sans",
        body: "Inter",
      },
      borderRadius: "lg",
      headerLayout: "standard",
      showAnnouncementBar: true,
      announcementText: "💼 ENTERPRISE READY: Professional auditing, branding, and digital transformation packages",
      announcementBg: "#1E3A8A",
      announcementTextColor: "#FFFFFF",
    },
    sections: [
      {
        id: "sec-hero",
        type: "hero",
        order: 1,
        visible: true,
        settings: { alignment: "left" },
        content: {
          badge: "EXCELLENCE IN ENTERPRISE SOLUTIONS",
          headline: "Accelerating Growth for Forward-Thinking Enterprises",
          subheadline: "Strategic advisory, financial consulting, legal compliance packages, and modern IT solutions designed to scale your enterprise.",
          primaryCtaText: "Explore Services",
          primaryCtaLink: "#products",
          secondaryCtaText: "Book Consultation",
          secondaryCtaLink: "#contact",
          imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80",
        },
      },
      {
        id: "sec-products",
        type: "product-grid",
        order: 2,
        visible: true,
        settings: { limit: 6, columns: 3 },
        content: {
          title: "Service Packages & Retainers",
          subtitle: "Turnkey enterprise packages tailored to your commercial stage",
        },
      },
      {
        id: "sec-contact",
        type: "contact",
        order: 3,
        visible: true,
        settings: {},
        content: {
          title: "Speak with a Senior Consultant",
          subtitle: "Schedule a confidential discovery meeting with our advisory team.",
        },
      },
    ],
  },
];

export function getStarterTemplateById(templateId: string): StoreTemplateDTO | undefined {
  return STARTER_TEMPLATES.find((t) => t.templateId === templateId || t.slug === templateId);
}
