from fpdf import FPDF
from datetime import datetime
import os
import logging
from utils.i18n import get_translator

# Set up logging
logger = logging.getLogger(__name__)

_ = get_translator()

def generate_payment_receipt_pdf(payment_record, student_info, course_name, output_path=".", logo_path=None):
    """
    Generates a PDF receipt for a student's payment.

    Args:
        payment_record (dict): A dictionary containing payment details.
        student_info (dict): A dictionary containing student details.
        course_name (str): The name of the course the payment is for.
        output_path (str): The directory where the PDF will be saved.
        logo_path (str, optional): The absolute path to the logo file.
    
    Returns:
        str: The full path to the generated PDF file, or None if an error occurs.
    """
    try:
        pdf = FPDF()
        pdf.add_page()
        # Use Helvetica instead of Arial for better compatibility with standard FPDF
        pdf.set_font("Helvetica", "B", 16)

        # EASI Logo (top-left)
        if logo_path and os.path.exists(logo_path):
            logger.debug(f"Attempting to embed logo from path: {logo_path}. File exists: {os.path.exists(logo_path)}")
            try:
                pdf.image(logo_path, x=10, y=10, w=30)
            except Exception as img_e:
                logger.error(f"Error embedding logo from {logo_path}: {img_e}")
        
        # Header
        pdf.set_xy(45, 15) # Position for title next to logo
        pdf.cell(0, 10, _("Payment Receipt"), 0, 1, 'C')
        pdf.set_font("Helvetica", "", 10)
        pdf.set_xy(10, 25) # Position for date below title
        pdf.cell(0, 5, _(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"), 0, 1, 'R')
        pdf.ln(10)

        # Receipt Details
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 7, _("Receipt Details:"), 0, 1, 'L')
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, _(f"Receipt Number: {payment_record.get('receipt_number', 'N/A')}"), 0, 1)
        pdf.cell(0, 7, _(f"Payment Date: {payment_record.get('payment_date', 'N/A')}"), 0, 1)
        pdf.cell(0, 7, _(f"Amount: Le {payment_record.get('amount', 0):,.2f}"), 0, 1)
        pdf.cell(0, 7, _(f"Payment Method: {payment_record.get('payment_method', 'N/A')}"), 0, 1)
        pdf.cell(0, 7, _(f"Status: {payment_record.get('status', 'N/A')}"), 0, 1)
        pdf.multi_cell(0, 7, _(f"Course: {course_name}"))
        pdf.ln(5)

        # Student Details
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 7, _("Student Details:"), 0, 1, 'L')
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, _(f"Name: {student_info.get('first_name', '')} {student_info.get('last_name', 'N/A')}"), 0, 1)
        pdf.cell(0, 7, _(f"Student ID: {student_info.get('student_id', 'N/A')}"), 0, 1)
        pdf.cell(0, 7, _(f"Email: {student_info.get('email', 'N/A')}"), 0, 1)
        pdf.cell(0, 7, _(f"Phone: {student_info.get('phone', 'N/A')}"), 0, 1)
        pdf.ln(10)

        # Footer
        pdf.set_font("Helvetica", "I", 8)
        pdf.cell(0, 10, _("Generated by EASI Student Management System"), 0, 0, 'C')

        # Create output directory if it doesn't exist
        os.makedirs(output_path, exist_ok=True)
        
        # Define filename
        filename = f"PaymentReceipt_{payment_record.get('receipt_number', 'NoReceipt')}_{student_info.get('student_id', 'NoID')}.pdf"
        full_output_path = os.path.join(output_path, filename)

        pdf.output(full_output_path)
        return full_output_path

    except Exception as e:
        logger.error(f"Error generating PDF payment receipt: {e}")
        return None

def generate_form_receipt_pdf(form_payment_record, student_info, output_path=".", logo_path=None):
    """
    Generates a PDF receipt for a student's form payment.

    Args:
        form_payment_record (dict): A dictionary containing form payment details.
        student_info (dict): A dictionary containing student details.
        output_path (str): The directory where the PDF will be saved.
        logo_path (str, optional): The absolute path to the logo file.
    
    Returns:
        str: The full path to the generated PDF file, or None if an error occurs.
    """
    try:
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 16)

        # EASI Logo (top-left)
        if logo_path and os.path.exists(logo_path):
            try:
                pdf.image(logo_path, x=10, y=10, w=30)
            except Exception as img_e:
                logger.error(f"Error embedding logo from {logo_path}: {img_e}")
        
        # Header
        pdf.set_xy(45, 15)
        pdf.cell(0, 10, _("Form Payment Receipt"), 0, 1, 'C')
        pdf.set_font("Helvetica", "", 10)
        pdf.set_xy(10, 25)
        pdf.cell(0, 5, _(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"), 0, 1, 'R')
        pdf.ln(10)

        # Receipt Details
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 7, _("Receipt Details:"), 0, 1, 'L')
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, _(f"Receipt Number: {form_payment_record.get('receipt_number', 'N/A')}"), 0, 1)
        pdf.cell(0, 7, _(f"Form Type: {form_payment_record.get('form_type', 'N/A')}"), 0, 1)
        pdf.cell(0, 7, _(f"Payment Date: {form_payment_record.get('payment_date', 'N/A')}"), 0, 1)
        pdf.cell(0, 7, _(f"Amount: Le {form_payment_record.get('amount', 0):,.2f}"), 0, 1)
        pdf.cell(0, 7, _(f"Payment Method: {form_payment_record.get('payment_method', 'N/A')}"), 0, 1)
        pdf.cell(0, 7, _(f"Status: {form_payment_record.get('status', 'N/A')}"), 0, 1)
        pdf.ln(5)

        # Student Details
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 7, _("Student Details:"), 0, 1, 'L')
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, _(f"Name: {student_info.get('first_name', '')} {student_info.get('last_name', 'N/A')}"), 0, 1)
        pdf.cell(0, 7, _(f"Student ID: {student_info.get('student_id', 'N/A')}"), 0, 1)
        pdf.ln(10)

        # Footer
        pdf.set_font("Helvetica", "I", 8)
        pdf.cell(0, 10, _("Generated by EASI Student Management System"), 0, 0, 'C')

        # Create output directory if it doesn't exist
        os.makedirs(output_path, exist_ok=True)
        
        # Define filename
        filename = f"FormReceipt_{form_payment_record.get('receipt_number', 'NoReceipt')}_{student_info.get('student_id', 'NoID')}.pdf"
        full_output_path = os.path.join(output_path, filename)

        pdf.output(full_output_path)
        return full_output_path

    except Exception as e:
        logger.error(f"Error generating PDF form receipt: {e}")
        return None

def generate_salary_receipt_pdf(salary_record, lecturer_info, output_path="."):
    """
    Generates a PDF receipt for a lecturer's salary payment.

    Args:
        salary_record (dict): A dictionary containing salary details
                              (e.g., 'receipt_number', 'payment_date', 'amount', 'status', 'notes').
        lecturer_info (dict): A dictionary containing lecturer details
                              (e.g., 'full_name', 'lecturer_id', 'email', 'department').
        output_path (str): The directory where the PDF will be saved.
    
    Returns:
        str: The full path to the generated PDF file, or None if an error occurs.
    """
    try:
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 16)

        # Header
        pdf.cell(0, 10, _("Salary Payment Receipt"), 0, 1, 'C')
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 5, _(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"), 0, 1, 'R')
        pdf.ln(10)

        # Receipt Details
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 7, _("Receipt Details:"), 0, 1, 'L')
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, _(f"Receipt Number: {salary_record.get('receipt_number', 'N/A')}"), 0, 1)
        pdf.cell(0, 7, _(f"Payment Date: {salary_record.get('payment_date', 'N/A')}"), 0, 1)
        pdf.cell(0, 7, _(f"Amount: Le {salary_record.get('amount', 0):,.2f}"), 0, 1)
        pdf.cell(0, 7, _(f"Status: {salary_record.get('status', 'N/A')}"), 0, 1)
        pdf.multi_cell(0, 7, _(f"Notes: {salary_record.get('notes', 'N/A')}"))
        pdf.ln(5)

        # Lecturer Details
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 7, _("Lecturer Details:"), 0, 1, 'L')
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, _(f"Name: {lecturer_info.get('full_name', 'N/A')}"), 0, 1)
        pdf.cell(0, 7, _(f"Lecturer ID: {lecturer_info.get('lecturer_id', 'N/A')}"), 0, 1)
        pdf.cell(0, 7, _(f"Email: {lecturer_info.get('email', 'N/A')}"), 0, 1)
        pdf.cell(0, 7, _(f"Department: {lecturer_info.get('department', 'N/A')}"), 0, 1)
        pdf.ln(10)

        # Footer
        pdf.set_font("Helvetica", "I", 8)
        pdf.cell(0, 10, _("Generated by EASI Student Management System"), 0, 0, 'C')

        # Create output directory if it doesn't exist
        os.makedirs(output_path, exist_ok=True)
        
        # Define filename
        filename = f"SalaryReceipt_{salary_record.get('receipt_number', 'NoReceipt')}_{lecturer_info.get('lecturer_id', 'NoID')}.pdf"
        full_output_path = os.path.join(output_path, filename)

        pdf.output(full_output_path)
        return full_output_path

    except Exception as e:
        logger.error(f"Error generating PDF receipt: {e}")
        return None

def generate_tailoring_receipt_pdf(payment_record, student_info, period, output_path=".", logo_path=None):
    """
    Generates a PDF receipt for a student's tailoring fee payment.
    """
    try:
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 16)

        # EASI Logo (top-left)
        if logo_path and os.path.exists(logo_path):
            try:
                pdf.image(logo_path, x=10, y=10, w=30)
            except Exception as img_e:
                logger.error(f"Error embedding logo from {logo_path}: {img_e}")
        
        # Header
        pdf.set_xy(45, 15)
        pdf.cell(0, 10, _("Tailoring Fee Receipt"), 0, 1, 'C')
        pdf.set_font("Helvetica", "", 10)
        pdf.set_xy(10, 25)
        pdf.cell(0, 5, _(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"), 0, 1, 'R')
        pdf.ln(10)

        # Receipt Details
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 7, _("Receipt Details:"), 0, 1, 'L')
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, _(f"Receipt Number: {payment_record.get('receipt_number', 'N/A')}"), 0, 1)
        pdf.cell(0, 7, _(f"Payment Date: {payment_record.get('payment_date', 'N/A')}"), 0, 1)
        pdf.cell(0, 7, _(f"Amount: Le {payment_record.get('amount', 0):,.2f}"), 0, 1)
        pdf.cell(0, 7, _(f"Fee Period: {period}"), 0, 1)
        pdf.cell(0, 7, _(f"Status: {payment_record.get('status', 'N/A')}"), 0, 1)
        pdf.ln(5)

        # Student Details
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 7, _("Student Details:"), 0, 1, 'L')
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, _(f"Name: {student_info.get('first_name', '')} {student_info.get('last_name', 'N/A')}"), 0, 1)
        pdf.cell(0, 7, _(f"Student ID: {student_info.get('student_id', 'N/A')}"), 0, 1)
        pdf.ln(10)

        # Footer
        pdf.set_font("Helvetica", "I", 8)
        pdf.cell(0, 10, _("Generated by EASI Student Management System"), 0, 0, 'C')

        # Create output directory if it doesn't exist
        os.makedirs(output_path, exist_ok=True)
        
        # Define filename
        filename = f"TailoringReceipt_{payment_record.get('receipt_number', 'NoReceipt')}_{student_info.get('student_id', 'NoID')}.pdf"
        full_output_path = os.path.join(output_path, filename)

        pdf.output(full_output_path)
        return full_output_path

    except Exception as e:
        logger.error(f"Error generating PDF tailoring receipt: {e}")
        return None
